#!/usr/bin/env node
/**
 * Page manifest: lists every page that exists in src/app, so the sitemap, service links, footer and
 * breadcrumbs follow what is actually deployed (a page folder that isn't in the build simply drops out).
 *
 * Runs automatically before `npm run dev`, `npm run build` and `npm run typecheck` (pre* scripts).
 * Writes src/lib/pages.generated.ts (gitignored). A page counts as noindex when its file sets `noindex: true`.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";

const APP = "src/app";
const OUT = "src/lib/pages.generated.ts";

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name);
    return e.isDirectory() ? walk(p) : e.name === "page.tsx" ? [p] : [];
  });
}

const pages = walk(APP)
  .map((file) => {
    const segments = relative(APP, file).split(sep).slice(0, -1);
    // Route groups like (legal) don't appear in the URL; dynamic [slug] routes can't be listed
    if (segments.some((s) => s.startsWith("[") || s.startsWith("_"))) return null;
    const path = "/" + segments.filter((s) => !/^\(.*\)$/.test(s)).join("/");
    return { path, noindex: /noindex:\s*true/.test(readFileSync(file, "utf8")) };
  })
  .filter(Boolean)
  .sort((a, b) => a.path.localeCompare(b.path));

writeFileSync(
  OUT,
  `// Generated by scripts/gen-pages.mjs from src/app. Do not edit.\n\nexport const builtPages: { path: string; noindex: boolean }[] = ${JSON.stringify(pages, null, 2)};\n`,
);
console.log(`[gen-pages] ${pages.length} pages → ${OUT}`);
