import { sharedReasons, type LicencePageData } from "./types";
import { link } from "./links";

/** L2 · FSSAI Registration (/chennai/fssai-registration). Primary keyword: "fssai registration in chennai". */
export const fssaiPage: LicencePageData = {
  id: "L2",
  service: "FSSAI Registration",
  meta: {
    title: "FSSAI Registration in Chennai | Food Licence | National Filings",
    description: "FSSAI registration and food licence in Chennai for restaurants, cloud kitchens, manufacturers and sellers. Right licence type, filed on FoSCoS with expert help.",
  },
  hero: {
    headline: { line1: "FSSAI Registration", line2Before: "", accent: "in Chennai" },
    sub: "Get the right FSSAI registration or food licence for your restaurant, kitchen, manufacturing unit or food business, filed correctly the first time.",
    badges: ["Right Licence Type", "FoSCoS Filing Support", "Renewal Reminders", "Transparent Process"],
    whatsapp: "Hi National Filings, I'd like a WhatsApp consultation about FSSAI registration.",
  },
  illustration: { icon: "UtensilsCrossed", kicker: "FSSAI", title: "Food Licence", line: "Your Kitchen · State", stamp: "Licensed", chips: ["Licence type chosen", "Food category set", "Premises verified"], steps: ["Details", "Type", "Filing", "Review", "Licence"] },
  benefitsSection: {
    title: "Benefits of FSSAI registration in Chennai",
    lead: "An FSSAI number is the legal licence to make, store or sell food, and customers look for it.",
    cta: { title: "Not sure which FSSAI licence you need?", sub: "Tell us what you sell and your expected turnover. We'll tell you whether you need basic registration, a state licence or a central licence.", message: "Hi National Filings, which FSSAI licence does my food business need?" },
  },
  benefits: [
    { icon: "ShieldCheck", title: "Legal right to operate", line: "Every food business in India needs FSSAI registration or a licence." },
    { icon: "BadgeCheck", title: "Customer trust", line: "The FSSAI number on your menu or pack shows food is from a licensed business." },
    { icon: "ShoppingCart", title: "Delivery apps and marketplaces", line: "Food delivery and ecommerce platforms ask for an FSSAI number before listing." },
    { icon: "Package", title: "Packaging and labelling", line: "Packaged food must carry your FSSAI number and logo on the label." },
    { icon: "Landmark", title: "Avoid penalties", line: "Running a food business without registration can lead to fines and closure." },
    { icon: "TrendingUp", title: "Room to grow", line: "Move from basic registration to a state or central licence as you scale." },
    { icon: "Store", title: "Retail and B2B supply", line: "Supermarkets, hotels and distributors prefer licensed suppliers." },
    { icon: "Award", title: "Brand credibility", line: "A clear licence history helps with investors, loans and franchise deals." },
  ],
  applicantsSection: { title: "Who needs FSSAI registration in Chennai", lead: "Anyone who makes, packs, stores, transports or sells food, from home kitchens to factories." },
  applicants: [
    { icon: "Soup", title: "Restaurants and hotels", line: "Dine-in, takeaway and hotel kitchens." },
    { icon: "ChefHat", title: "Cloud kitchens", line: "Delivery-only kitchens on food apps." },
    { icon: "Home", title: "Home-based food sellers", line: "Bakers, caterers and tiffin services." },
    { icon: "Factory", title: "Food manufacturers", line: "Processing units and packaged food makers." },
    { icon: "Store", title: "Retailers and grocers", line: "Shops, supermarkets and sweet stalls." },
    { icon: "Truck", title: "Distributors and transporters", line: "Wholesale, storage and cold chain." },
    { icon: "ShoppingCart", title: "Online food brands", line: "D2C brands and marketplace sellers." },
    { icon: "Coffee", title: "Cafes and food trucks", line: "Small outlets, kiosks and carts." },
  ],
  highlights: {
    eyebrow: "Licence types",
    title: "Which FSSAI licence do you need in Chennai?",
    lead: "The type depends mainly on your annual turnover and what you do. We confirm it before filing.",
    items: [
      { icon: "Store", label: "Small businesses", title: "Basic registration", line: "For small food businesses with lower turnover, such as home sellers, small shops and stalls." },
      { icon: "Building2", label: "Most growing businesses", title: "State licence", line: "For medium-sized restaurants, manufacturers and distributors operating within Tamil Nadu.", highlight: true },
      { icon: "Globe", label: "Large or multi-state", title: "Central licence", line: "For large businesses, importers, exporters and some ecommerce and multi-state operations." },
      { icon: "RefreshCw", label: "Before expiry", title: "Renewal and modification", line: "Renew before your licence expires, and update it when products, premises or capacity change." },
    ],
  },
  documentsSection: { title: "Documents required for FSSAI registration in Chennai", lead: "Basic registration needs very little; licences need a few more details about your premises." },
  documents: [
    { icon: "UserRound", title: "For basic registration", items: ["Photo ID of the owner", "Passport-size photo", "Address proof of the premises", "List of food products"], hint: "Most small food businesses start here." },
    { icon: "Building2", title: "For a state or central licence", items: ["Business registration proof", "Layout plan of the premises", "List of equipment", "Water test report, if you manufacture", "Food safety management plan"], hint: "The exact list depends on your category; we tell you what applies." },
  ],
  documentsNote: { title: "Applications are filed online on FoSCoS", sub: "Share scans on WhatsApp and we prepare and file the application for you.", message: "Hi National Filings, I'd like to send my documents for FSSAI registration." },
  processSection: {
    title: "FSSAI registration process in Chennai",
    lead: "Five steps from your details to the FSSAI number.",
    cta: { title: "Ready to get your food licence?", sub: "Share your business details and we'll start the application today.", message: "Hi National Filings, I'm ready to apply for FSSAI registration. Can we start?" },
  },
  steps: [
    { title: "Business details", time: "Day 1", sub: "We understand your food business, products and premises." },
    { title: "Licence type and category", time: "Same day", sub: "We confirm basic, state or central and the right food category." },
    { title: "Application filing", time: "1-2 days", sub: "We prepare documents and file the application on FoSCoS." },
    { title: "Department review", time: "Varies by type", sub: "The food safety department reviews it and may inspect licensed premises." },
    { title: "Registration or licence issued", time: "On approval", sub: "You receive your FSSAI certificate with its number." },
  ],
  processNote: "Basic registrations are usually faster; state and central licences take longer and can involve an inspection. Timelines depend on the food safety department.",
  mistakesSection: { title: "Common FSSAI registration mistakes in Chennai", lead: "These errors lead to rejections, wrong licences or penalties later. We check each one." },
  mistakes: [
    { icon: "Shuffle", title: "Wrong licence type", problem: "Taking basic registration when your turnover or activity needs a state or central licence.", fix: "We check turnover, activity and locations to pick the right licence." },
    { icon: "ListTree", title: "Wrong food category", problem: "Products listed under a category that doesn't match what you make or sell.", fix: "We map every product to the correct food category before filing." },
    { icon: "FileWarning", title: "Incomplete premises details", problem: "Address or layout details that don't match the documents.", fix: "We match every detail against your premises documents." },
    { icon: "Clock", title: "Missing renewal", problem: "Letting the licence expire while still trading.", fix: "We track your expiry date and file the renewal in time." },
  ],
  costSection: {
    title: "FSSAI registration cost factors in Chennai",
    lead: "Government fees are set by FSSAI and shown separately. Our fee is quoted upfront.",
    cta: { title: "Get an exact quote for your FSSAI licence", sub: "Tell us your business type and we'll share the government fee and our fee before starting.", message: "Hi National Filings, can I get a quote for FSSAI registration?" },
  },
  costs: [
    { icon: "Landmark", label: "Set by FSSAI", highlight: true, title: "Government fees", line: "Depend on the licence type and how many years you register for. Paid directly on FoSCoS." },
    { icon: "Headset", label: "Quoted upfront", title: "Professional assistance", line: "Covers choosing the licence, preparing documents, filing and follow-up." },
    { icon: "FilePen", label: "If needed", title: "Modifications", line: "Changes to products, premises or capacity after the licence is issued." },
    { icon: "RefreshCw", label: "Periodic", title: "Renewals", line: "Renewal before expiry keeps your licence valid without a gap." },
  ],
  reasonsTitle: "Why choose National Filings for FSSAI registration in Chennai",
  reasons: sharedReasons,
  faqTitle: "FSSAI registration in Chennai: your questions",
  faqs: [
    { q: "What is FSSAI registration?", a: "FSSAI registration is the licence every food business in India needs from the Food Safety and Standards Authority of India. Small businesses get a basic registration; larger ones get a state or central licence. Each comes with a number you must display." },
    { q: "Who needs an FSSAI licence in Chennai?", a: "Anyone who makes, processes, packs, stores, transports, distributes or sells food, including restaurants, cloud kitchens, home bakers, grocers, manufacturers and online food sellers." },
    { q: "Which FSSAI licence do I need?", a: "It depends mainly on your annual turnover and activity. Small businesses usually need basic registration, medium businesses a state licence, and large, import or multi-state businesses a central licence. We confirm the right one before filing." },
    { q: "How long does FSSAI registration take?", a: "Basic registration is usually quicker. State and central licences take longer because the department reviews the application and may inspect the premises. We file promptly and follow up until it's issued." },
    { q: "Can I get an FSSAI licence for a home kitchen?", a: "Yes. Home bakers, caterers and tiffin services can get FSSAI registration for the home premises they cook from." },
    { q: "Do I need FSSAI to sell on Swiggy, Zomato or Amazon?", a: "Yes. Food delivery apps and ecommerce marketplaces ask for a valid FSSAI number before they list your food business." },
    { q: "How long is an FSSAI licence valid?", a: "You choose a validity period when you apply, from one to several years, and renew it before it expires." },
    { q: "What happens if I run a food business without FSSAI?", a: "Operating without registration or a licence can lead to penalties and the business being stopped. Getting registered before you start is far cheaper." },
    { q: "Can I change my FSSAI licence later?", a: "Yes. You can modify it when you add products, change premises or increase capacity, and upgrade from basic registration to a licence as you grow." },
    { q: "How can National Filings help with FSSAI registration in Chennai?", a: "We choose the right licence and food categories, prepare your documents, file on FoSCoS, follow up with the department and remind you before renewal." },
  ],
  related: [
    { icon: "Factory", label: "MSME registration", href: link("L1") },
    { icon: "ScrollText", label: "Trade license", href: link("L3") },
    { icon: "ReceiptIndianRupee", label: "GST consultant", href: link("P2") },
    { icon: "ShieldCheck", label: "Trademark registration", href: link("P5") },
  ],
  final: { title: "Get your FSSAI licence in Chennai today", sub: "Talk with our experts and get the right food licence filed quickly and correctly.", message: "Hi National Filings, I'd like to get FSSAI registration for my food business. Please guide me." },
  catalogue: ["FSSAI basic registration", "FSSAI state licence", "FSSAI central licence", "FSSAI renewal"],
};
